[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
test = false
bench = false
name = "kernel"

[lib]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
crate-type = ["staticlib"]

[dependencies]
common = { path = "../common" }


