[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "loader"
path = "src/main.rs"
test = false
bench = false

[dependencies]
elf = { version = "0.7.4", default-features = false }
multiboot = "0.8.0"
